# Generated by Django 5.2.8 on 2025-11-30 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Official name of the park', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(help_text='Geographic latitude in decimal degrees')),
                ('longitude', models.FloatField(help_text='Geographic longitude in decimal degrees')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'parks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkDescription',
            fields=[
                ('Park', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mapping.park')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, help_text='Full address of the park', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='park_images/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text="User's comments about the park")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Moderation status')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='mapping.park')),
            ],
            options={
                'verbose_name_plural': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
