# Generated by Django 5.2.8 on 2025-11-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_parkdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkdescription',
            name='name',
        ),
        migrations.AddField(
            model_name='parkdescription',
            name='Park',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mapping.park'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkdescription',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
